databases:
  - name: messenger-db
    databaseName: messenger
    user: messenger

services:
  - type: web
    name: messenger
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn web_messenger.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: messenger-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ENV
        value: production
    autoDeploy: false
